### ISSUE TITLE
Final Check - Multiple Issues #9

### ISSUE THREAD

**Issue by taruch** [taruch/phantom_ciscorouter_rtbh#1]
ctions:

Add "primary": true to the ip parameter for block/unblock ip
Change "read_only": true" for block ip, unblock ip, block network, unblock network to "read_only": false"
Change the name of list blocked networks action to list networks
Actions block ip, unblock ip, block network, unblock network are missing render dictionaries and output lists
JSON:

App Version in ciscorouter_rtbh.json is missing a closing double-quote for the value.
Documentation:

Reduce the app description to just one sentence. When this gets published to the portal, multiple sentences will end up wrapping, and the description should only contain a single sentence allowing a user to get an OK understanding of what the app does. I think that you could leave it to:
This app interfaces with Cisco IOS-XE devices to create a blackhole for configured IPs or networks in Cisco BGP networks.
You could add the rest of the description to a readme.html file within the app directory. The backend will automagically render it below the description.
screen shot 2016-12-14 at 11 24 16 am

**Comment by taruch** [comment]
Add "primary": true to the ip parameter for block/unblock ip
  - Completed

Change "read_only": true" for block ip, unblock ip, block network, unblock network to "read_only": false"
  - Completed

Change the name of list blocked networks action to list networks
  - Completed

Add “ip” and “ip network” as contains to the actions that it fits.  Validation of ip network is optional on your part.  But’s its on our roadmap as a feature sometime soon
  - Completed

Reduce the app description to just one sentence. 
  - Completed

Actions block ip, unblock ip, block network, unblock network are missing render dictionaries and output lists
  - Not done

**Comment by codejulen** [comment]
Hey Todd, any update on that last issue? (render dictionary and output lists)

**Comment by taruch** [comment]
Completed render dictionary and output lists.
