### ISSUE TITLE
Test connectivity output

### ISSUE THREAD

**Issue by joelwking** [taruch/phantom_ciscorouter_rtbh#2]
When I tested connectivity, my CSR console indicated a connect / disconnect.

> *Sep 13 15:16:14.058: %ONEP_BASE-6-CONNECT: [Element]: ONEP session Application:restApp-9227559889 Host:dummy ID:6108 User:admin has connected.
> *Sep 13 15:16:14.060: %ONEP_BASE-6-DISCONNECT: [Element]: ONEP session Application:restApp-9227559889 Host:dummy ID:6108 User:admin has disconnected.
> and the dialog box reported
> 
> App 'Cisco Cloud Services Router' started successfully. Parameters for 'test connectivity' sent
> Loaded action execution configuration

But I am not seeing a message return to the GUI. You did code 

`return self.set_status_save_progress(phantom.APP_SUCCESS, "Received token from device")`

I am running version 2.0.67

**Comment by taruch** [comment]
Resolved.  You should now get either a:
"SUCCESS!  Connected to device" or a
"FAILURE!  Unable to connect to device"
in the GUI.
