### ISSUE TITLE
undefined name 'IP'

### ISSUE THREAD

**Issue by joelwking** [taruch/phantom_ciscorouter_rtbh#3]
Cloned your repository into phantom 2-0-264 and attempted to compile

[phantom@phantom2-0-264 phantom_cisco_csr]$ ../compile_app.py -i
cd'ing into ./
Compiling: ./**init**.py
Compiling: ./cisco_csr_consts.py
./cisco_csr_consts.py:24:1: F821 undefined name 'IP'

Exiting...

**Comment by taruch** [comment]
cisco_csr_consts.py has been removed.  Application compiles without error.
