### ISSUE TITLE
Please add "contains" types

### ISSUE THREAD

**Issue by ryanlrussell** [taruch/phantom_ciscorouter_rtbh#5]
Version 1.6

Hi, this is Ryan from Phantom. Thanks for the new Phantom App, this is great! We frequently have a look at new Phantom apps to see if we can make any suggestions or improvements. So please take any issues I file as a simple suggestion. Also, if you do end up making a change, please remember to bump the version number.

I noticed that you don't seem to have any "contains" fields on any of your action parameters. If you're not familiar with how contains works in Phantom, it's basically the "type" for a given field. Phantom uses these for making context actions available in the UI.

Your destination_network parameters for the block ip and unblock ip actions should have a contains type of "ip". This will make it so the context menu on fields in the UI marked as "ip" will have your block ip/unblock ip actions available.

![screen shot 2016-10-21 at 5 33 49 pm](https://cloud.githubusercontent.com/assets/1728937/19615491/ab70f6ae-97b4-11e6-8a72-71154835c805.png)
![screen shot 2016-10-21 at 5 34 18 pm](https://cloud.githubusercontent.com/assets/1728937/19615494/afe3a65a-97b4-11e6-9242-61c92350b57e.png)

Here's a screenshot of what I'm talking about. There's the context menu, and notice on the Launch Action dialog that there's no Cisco CSR Asset shown.

But if we edit the JSON to include a contains for those actions, like this for block IP:

```
  "action": "block ip",
  "description": "Blocks an IP",
  "type": "contain",
  "identifier": "block_ip",
  "read_only": true,
  "parameters": {
     "destination_network": {
       "contains": [ "ip" ],
       "description": "IP to block (X.X.X.X)",
       "data_type": "string",
       "required": true
```

Now the asset for your app will show:

![screen shot 2016-10-21 at 5 46 57 pm](https://cloud.githubusercontent.com/assets/1728937/19615603/6f1096fe-97b6-11e6-975f-3f2e820cebf9.png)

The "ip" contains is probably the most common type we have, so that one is easy to recommend. However, we don't have any other apps with a type for ip/netmask. So if you were wanting to address those fields (looks like you use destination_network), you could do three things; Leave it as-is without one, make a new one (I might suggest "cidr"), or you could break the IP and mask parts into two fields, ip and mask, and then use a contains of "ip" for the IP part.

**Comment by taruch** [comment]
Resolved in 
commit 279159714810cff49a983fdc92fec3cbcf27028b (block_ip)
and 
commit 8cfda435b9bc71001340acf54426eb7b1840a93a (unblock_ip_
