### ISSUE TITLE
Please change Product Vendor to Cisco Systems

### ISSUE THREAD

**Issue by ryanlrussell** [taruch/phantom_ciscorouter_rtbh#6]
Version 1.6

You currently have your App vendor listed as "Cisco", while all the other Cisco product apps are listed as "Cisco Systems":

![screen shot 2016-10-21 at 6 11 41 pm](https://cloud.githubusercontent.com/assets/1728937/19615788/dfb73ffe-97b9-11e6-977a-250d14855b48.png)
![screen shot 2016-10-21 at 6 11 47 pm](https://cloud.githubusercontent.com/assets/1728937/19615791/e484a9fe-97b9-11e6-852a-31045c3ec8c9.png)

Please change 
"product_vendor": "Cisco",

to

"product_vendor": "Cisco Systems",

Thanks!

**Comment by taruch** [comment]
Resolved in commit 279159714810cff49a983fdc92fec3cbcf27028b
