### ISSUE TITLE
Please re-arrange Asset parameters and maybe name

### ISSUE THREAD

**Issue by ryanlrussell** [taruch/phantom_ciscorouter_rtbh#7]
Version 1.6

I'm not familiar with the CSR product, mostly the older routers. So I could easily be misunderstanding. If so, please close and ignore.

Here's your current Asset config layout:

![screen shot 2016-10-21 at 6 27 00 pm](https://cloud.githubusercontent.com/assets/1728937/19615900/00cd182e-97bc-11e6-9603-e93b5819c3ba.png)

The user and password are fairly self-explanatory. The Trigger Host must be the IP or hostname.

It's possible to order these fields into the order that you want. Most asset types have the IP/hostname field on the first line, and then username and password on a row together below that.

To do that in your case, that would look like this:

  "configuration": {
    "route_to_null": {
      "description": "Null Route IP (x.x.x.x)",
      "order": 5,
      "data_type": "string",
      "required": true
    },
      "trigger_host": {
        "description": "Trigger Host",
        "order": 0,
        "data_type": "string",
        "required": true
    },
      "ph": {
        "data_type": "ph",
        "order": 1
      },
      "tag": {
        "description": "Route Tag",
        "order": 4,
        "data_type": "string",
        "required": false
    },
      "user": {
        "description": "User with access to the trigger node",
        "order": 2,
        "data_type": "string",
        "required": true
    },
      "password": {
        "description": "Password",
        "order": 3,
        "data_type": "password",
        "required": true
    }
  },

Which gives you:

![screen shot 2016-10-21 at 6 39 08 pm](https://cloud.githubusercontent.com/assets/1728937/19616001/eab05c2a-97bd-11e6-84ad-7fecbff054fa.png)

(The "ph" field stands for "placeholder", and it's a blank invisible field to force username and password to start on the next line.)

**Comment by ryanlrussell** [comment]
Oh, forgot about the names. Again, not familiar with the CSR, but is there a reason for not using the traditional ip/hostname, username and password field names?

**Comment by taruch** [comment]
Resolved in commit 279159714810cff49a983fdc92fec3cbcf27028b
