### ISSUE TITLE
Please change App type

### ISSUE THREAD

**Issue by ryanlrussell** [taruch/phantom_ciscorouter_rtbh#8]
Version 1.6

The current type is "information service":

"type": "information service",

This doesn't seem correct. The other Cisco products are usually listed as "Firewall" (even if that's not quite correct.. the actions we expose for the Catalyst are firewall-like)

![screen shot 2016-10-21 at 6 46 14 pm](https://cloud.githubusercontent.com/assets/1728937/19616051/c5459d96-97be-11e6-9512-a5218bb64e3f.png)

I would suggest your App be Firewall as well:

"type": "firewall",

Thanks!

**Comment by taruch** [comment]
resolved in commit cb04a17ccba07c5c3979bcbeb1b62100fb21399b
